language: node_js
node_js: stable

install:
  - npm install -g bower purescript pulp
  - make clean init

script:
  - make build test

deploy:
  provider: script
  script: make release
  on:
    branch: master
