version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.7.1

    steps:
      - checkout

      - run: npm install -g bower purescript pulp
      - run: make clean init
      - run: make build test
